### ISSUE TITLE
A typo in README

### ISSUE THREAD

**Issue by gamtiq** [gocanto/js-validator#10]
There is a typo in `README.md`:

> that does not _me_ the rules

**Comment by gocanto** [comment]
Would you like to send a PR?

**Comment by gamtiq** [comment]
I suppose that such a trivial change does not need PR. :-)
But if you would like, I can make PR.

**Comment by gocanto** [comment]
Lol, let me do it then.. you are right! I am just a lazy person tho

**Comment by gocanto** [comment]
fixed #11
