### ISSUE TITLE
demo is not working from npm install

### ISSUE THREAD

**Issue by sanbeaman** [gocanto/js-validator#9]
Hello,
I've been trying to figure out the best way to validate forms with vue and laravel.
Your project looks really promising.  However, I can't get your demo to work.

> Browserify Failed!: Cannot find module 'easiest-js-validator'

Often times when I can't get a package to work, i'll have to copy the main file or folder into the same folder as my main.js file. ( Some gulp or vueify issue...)
It's not clear  to me which file(s), I should move if any ...

Should there be a **'dist'** folder in your package, that contains **easiest-js-validator.js** file?
your demo references it but it's not on git or in node package.

in your package.json  the main file is listed as:

> "main": "src/js/index.js",

but there isn't an index.js file in package..

should the package contain easiest-js-validator.js file or index.js file?
 if not .. could you advise..
thanks
drew

**Comment by gocanto** [comment]
Hi @sanbeaman,

The way how I compile the `demo` is written in the `gulpfile.js`

``` js
mix.browserify('demo.js', 'dist/easiest-js-validator.js');
```

 <a href="https://github.com/gocanto/easiest-js-validator/blob/master/gulpfile.js#L8">inlustration</a>

If you check the demo file used within gulp you will see that the lib is imported in its top, as so: 

``` js
import Validator from 'easiest-js-validator';
```

<a href="https://github.com/gocanto/easiest-js-validator/blob/master/src/js/demo.js#L2">inlustration</a>

---

If these lines did not help you out, you will have to post the error you are having. 

Let me know.

**Comment by sanbeaman** [comment]
Thanks for reply.
Ok - so I need to build the validator file with gulp. (First time only)
then import  and incorporate it into my vue component... then gulp /
browserify

I'll take another look later on.  Thank you

On Jul 13, 2016 17:53, "Gustavo Ocanto" notifications@github.com wrote:

Hi @sanbeaman https://github.com/sanbeaman,

The way how I compile the demo is written in the gulpfile.js

mix.browserify('demo.js', 'dist/easiest-js-validator.js');

inlustration
https://github.com/gocanto/easiest-js-validator/blob/master/gulpfile.js#L8

If you check the demo file used within gulp you will see that the lib is
imported in its top, as so:

import Validator from 'easiest-js-validator';

inlustration

## https://github.com/gocanto/easiest-js-validator/blob/master/src/js/demo.js#L2

If these lines did not help you out, you will have to post the error you
are having.

Let me know.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/gocanto/easiest-js-validator/issues/9#issuecomment-232498344,
or mute the thread
https://github.com/notifications/unsubscribe/AAI-Sr_OHUyHzEkbKZ3DZHXTv988e1H5ks5qVV51gaJpZM4JLxLb
.

**Comment by gocanto** [comment]
Ok
